# Generated by Django 6.0.2 on 2026-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('additional_contacts', models.JSONField(blank=True, default=list)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('upi', 'UPI'), ('cash', 'Cash')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_image', models.URLField(blank=True, null=True)),
                ('sign_image', models.URLField(blank=True, null=True)),
                ('auto_stock', models.BooleanField(default=True)),
                ('auto_transaction', models.BooleanField(default=True)),
                ('enable_po', models.BooleanField(default=False)),
                ('enable_quotation', models.BooleanField(default=False)),
                ('enable_pi', models.BooleanField(default=False)),
                ('enable_challan', models.BooleanField(default=False)),
                ('enable_vouchers', models.BooleanField(default=False)),
                ('enable_interest', models.BooleanField(default=False)),
                ('enable_cn', models.BooleanField(default=False)),
                ('enable_dn', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
