# Generated by Django 6.0.2 on 2026-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='header_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sign_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
