# Generated by Django 6.0.8 on 2026-10-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_settings_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='settings',
            name='company_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='settings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='letterhead_footer_mm',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='letterhead_height_mm',
            field=models.PositiveSmallIntegerField(default=32),
        ),
        migrations.AddField(
            model_name='settings',
            name='letterhead_mode',
            field=models.CharField(choices=[('banner', 'Header banner'), ('page', 'Full-page letterhead')], default='banner', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='print_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='signatory_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
