# Generated by Django 6.0.8 on 2026-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_settings_company_address_settings_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='print_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern')], default='modern', max_length=10),
        ),
    ]
