# Generated by Django 6.0.2 on 2026-02-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='is_doc_deleted',
        ),
    ]
