# Generated by Django 6.0.2 on 2026-02-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_document_is_active'),
        ('inventory', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='accounting.document'),
        ),
    ]
