# Generated by Django 6.0.2 on 2026-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocktransaction_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_document_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
