# Generated by Django 6.0.2 on 2026-02-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('upi', 'UPI'), ('cash', 'Cash')], max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bill', 'Bill'), ('invoice', 'Invoice'), ('po', 'Purchase Order'), ('pi', 'Performa Invoice'), ('challan', 'Challan'), ('quotation', 'Quotation'), ('cn', 'Credit Note'), ('dn', 'Debit Note'), ('cash_voucher', 'Cash Voucher'), ('income_voucher', 'Income Voucher'), ('interest', 'Interest')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('line_items', models.JSONField(blank=True, default=list, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('charges', models.JSONField(blank=True, default=list, null=True)),
                ('taxes', models.JSONField(blank=True, default=list, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('header_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('signature_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('attachment_urls', models.JSONField(blank=True, default=list, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee_documents', to='contacts.contact')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contacts.contact')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_documents', to='accounting.document')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('record', 'Record'), ('payment', 'Payment'), ('contra', 'Contra')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monthly_cumulative_delta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contacts.contact')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.document')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.paymentaccount')),
            ],
            options={
                'ordering': ['transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['contact', 'transaction_date'], name='accounting__contact_37fff2_idx'), models.Index(fields=['payment_account', 'transaction_date'], name='accounting__payment_99f4ac_idx'), models.Index(fields=['transaction_type', 'transaction_date'], name='accounting__transac_a02795_idx')],
            },
        ),
    ]
