# Generated by Django 6.0.2 on 2026-02-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bill', 'Bill'), ('invoice', 'Invoice'), ('po', 'Purchase Order'), ('pi', 'Proforma Invoice'), ('quotation', 'Quotation'), ('challan', 'Challan'), ('cn', 'Credit Note'), ('dn', 'Debit Note'), ('cash_payment_voucher', 'Cash Payment Voucher'), ('cash_receipt_voucher', 'Cash Receipt Voucher'), ('interest', 'Interest'), ('expense', 'Expense')], max_length=30)),
                ('doc_id', models.CharField(max_length=50, unique=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('charges', models.JSONField(blank=True, default=list)),
                ('taxes', models.JSONField(blank=True, default=list)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_urls', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee_documents', to='shared.contact')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='shared.contact')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='accounting.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('record', 'Record'), ('actual', 'Actual'), ('contra', 'Contra')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monthly_cumulative_delta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_doc_deleted', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shared.contact')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.document')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shared.paymentaccount')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
