# Generated by Django 6.0.2 on 2026-02-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransaction',
            name='is_doc_deleted',
        ),
    ]
