# Generated by Django 6.0.2 on 2026-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_financialtransaction_is_doc_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
