# Generated by Django 6.0.2 on 2026-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_document_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
