# Generated by Django 6.0.8 on 2026-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stock_mode',
            field=models.CharField(blank=True, choices=[('none', 'No stock'), ('record', 'Move stock later'), ('actual', 'Automatic stock')], max_length=10, null=True),
        ),
    ]
