# Generated by Django 6.0.8 on 2026-10-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_document_stock_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounting.document')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.financialtransaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payment', 'document'), name='unique_payment_document_allocation')],
            },
        ),
    ]
