# Generated by Django 6.0.8 on 2026-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_backfill_payment_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='transfer_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
