# Generated by Django 6.0.8 on 2026-10-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_financialtransaction_is_reversed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reverse_charge',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
