# Generated by Django 6.0.8 on 2026-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_document_place_of_supply_document_reverse_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='supply_category',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable domestic'), ('nil_rated', 'Nil rated'), ('exempt', 'Exempt'), ('non_gst', 'Non GST'), ('export', 'Export'), ('import', 'Import')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tax_mode',
            field=models.CharField(choices=[('document', 'Whole document'), ('item', 'Per item')], default='document', max_length=10),
        ),
    ]
