# Generated by Django 6.0.8 on 2026-10-06 06:49

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_document_supplier_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=20)),
                ('snapshot', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_fields', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='accounting.document')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
