# Generated by Django 6.0.8 on 2026-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_documentrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
