# Generated by Django 6.0.8 on 2026-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_document_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('bill', 'Bill'), ('invoice', 'Invoice'), ('po', 'Purchase Order'), ('pi', 'Proforma Invoice'), ('quotation', 'Quotation'), ('challan', 'Challan'), ('cn', 'Credit Note'), ('dn', 'Debit Note'), ('cash_payment_voucher', 'Cash Payment Voucher'), ('cash_receipt_voucher', 'Cash Receipt Voucher'), ('interest', 'Interest'), ('expense', 'Expense'), ('income', 'Income')], max_length=30),
        ),
    ]
